### ISSUE TITLE
File gets emptied when serializing something unexpected

### ISSUE THREAD

**Issue by TheAlternateDoctor** [patataofcourse/flour#1]
While serializing a file that isn't a bccad or a brcad, the json file immediately gets overwritten with nothing.
This also happens in reverse, trying to deserializing a file that isn't a json. The bccad gets emptied.

Output from the terminal
```bash
$ ./flour serialize arc/golf_monkey.json
Error: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
```
The resulting golf_monkey.json ends up being empty.

**Comment by patataofcourse** [comment]
If this still doesn't work, I'll reopen, but for now it should be fine.
